### ISSUE TITLE
cuSolver error

### ISSUE THREAD

**Issue by AnjaliSetiya** [kalininalab/alphafold_non_docker#22]
i was able to run alphafold on cpu successfully.
but when i am trying to run the same on gpu i am getting the below error

 **Traceback (most recent call last):
  File "/home/ngayatri/alphafold/run_alphafold.py", line 310, in <module>
    app.run(main)
  File "/home/ngayatri/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/ngayatri/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/ngayatri/alphafold/run_alphafold.py", line 284, in main
    predict_structure(
  File "/home/ngayatri/alphafold/run_alphafold.py", line 149, in predict_structure
    prediction_result = model_runner.predict(processed_feature_dict)
  File "/home/ngayatri/alphafold/alphafold/model/model.py", line 133, in predict
    result = self.apply(self.params, jax.random.PRNGKey(0), feat)
  File "/home/ngayatri/miniconda3/envs/alphafold/lib/python3.8/site-packages/jaxlib/cusolver.py", line 281, in syevd
    lwork, opaque = cusolver_kernels.build_syevj_descriptor(
RuntimeError: cuSolver internal error**

i have checked with cuda version also. it is present 

thank you

**Comment by sanjaysrikakulam** [comment]
Hi @AnjaliSetiya 

Please refer to this issue #15
