### ISSUE TITLE
alphafold.data.tools

### ISSUE THREAD

**Issue by as7a5** [kalininalab/alphafold_non_docker#42]
Hi After the installation I get error as:

Traceback (most recent call last):
  File "/gpfs/home/js12009/Projects/Projects/AlphaFold_TEST/AlphaFold_2_2_0/Basic/run_alphafold.py", line 31, in <module>
    from alphafold.data import pipeline
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/envs/alphafold2.2/lib/python3.8/site-packages/alphafold/data/pipeline.py", line 26, in <module>
    from alphafold.data import templates
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/envs/alphafold2.2/lib/python3.8/site-packages/alphafold/data/templates.py", line 31, in <module>
    from alphafold.data.tools import kalign
ModuleNotFoundError: No module named 'alphafold.data.tools'

is there a python or conda library I am missing in the installation? 
Previous steps:
from alphafold.common import protein
from alphafold.common import residue_constants
seem to work.

**Comment by as7a5** [comment]
Previous steps:
from alphafold.common import protein
from alphafold.common import residue_constants
from alphafold.data import pipeline
from alphafold.data import pipeline_multimer
from alphafold.data import templates
seem to work.

**Comment by sanjaysrikakulam** [comment]
Hi @as7a5 

Sorry for the delayed response. I am not sure how you have installed AF2, I do not see any such error by following the steps in the README of this repository. 

Please make sure you have installed all dependencies as provided in the README and redownload the AF2 latest version and try to rerun and see if you still have the error.
