### ISSUE TITLE
Error with Amber minimization toggle while running in multimer mode

### ISSUE THREAD

**Issue by jcs0902** [kalininalab/alphafold_non_docker#43]
I have been working to get both monomer and multimer predictions running on my schools HPC, but I continue to run into the same error with amber relaxation: 

Error initializing CUDA: CUDA error (34) at /home/conda/feedstock_root/build_artifacts/openmm_1622798701405/work/platforms/cuda/src/CudaContext.cpp:138
Traceback (most recent call last):
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/envs/alphafold220/alphafold-2.2.0/run_alphafold.py", line 422, in <module>
    app.run(main)
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/envs/alphafold220/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/envs/alphafold220/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/envs/alphafold220/alphafold-2.2.0/run_alphafold.py", line 398, in main
    predict_structure(
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/envs/alphafold220/alphafold-2.2.0/run_alphafold.py", line 242, in predict_structure
    relaxed_pdb_str, _, _ = amber_relaxer.process(prot=unrelaxed_protein)
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/envs/alphafold220/alphafold-2.2.0/alphafold/relax/relax.py", line 61, in process
    out = amber_minimize.run_pipeline(
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/envs/alphafold220/alphafold-2.2.0/alphafold/relax/amber_minimize.py", line 475, in run_pipeline
    ret = _run_one_iteration(
  File "/gpfs/share/apps/miniconda3/gpu/4.9.2/envs/alphafold220/alphafold-2.2.0/alphafold/relax/amber_minimize.py", line 419, in _run_one_iteration
    raise ValueError(f"Minimization failed after {max_attempts} attempts.")
ValueError: Minimization failed after 100 attempts.

This error can be avoided in monomer predictions by setting the "-r" flag to false, but setting this flag to false in the multimer mode doesn't change anything and I receive the same error that I was getting before.

This is also a general issue in that amber relaxation will not work for either of the modes and if there is a solution, please let me know!

**Comment by sanjaysrikakulam** [comment]
Hi @jcs0902 

Sorry for the delayed response. I am not sure if I can help on this matter, please see if you can create an issue on the AF2 github repo, maybe they can help?

These are the tickets that already discuss this problem.
1. https://github.com/deepmind/alphafold/issues/482
2. https://github.com/deepmind/alphafold/issues/343
3. https://github.com/deepmind/alphafold/issues/466
