### ISSUE TITLE
ValueError: Could not find HHsearch database ./alphafold_data/pdb70/pdb70

### ISSUE THREAD

**Issue by pariskang** [kalininalab/alphafold_non_docker#47]
I installed alphafold_non_docker step by step, but I found an error as the following:
```
(alphafold) [root@ecs alphafold-2.2.0]# bash run_alphafold.sh -d ./alphafold_data -o ./dummy_test/ -f ./example/query.fasta -t 2020-05-14 -g False
E0704 11:23:00.766234 139973713471296 hhsearch.py:56] Could not find HHsearch database ./alphafold_data//pdb70/pdb70
Traceback (most recent call last):
  File "/root/alphafold-2.2.0/run_alphafold.py", line 422, in <module>
    app.run(main)
  File "/root/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/root/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/root/alphafold-2.2.0/run_alphafold.py", line 327, in main
    template_searcher = hhsearch.HHSearch(
  File "/root/alphafold-2.2.0/alphafold/data/tools/hhsearch.py", line 57, in __init__
    raise ValueError(f'Could not find HHsearch database {database_path}')
ValueError: Could not find HHsearch database ./alphafold_data/pdb70/pdb70

```
How to resolve this problem, I sincerely need u help. Thank u~

**Comment by sanjaysrikakulam** [comment]
Hi @pariskang 

Please make sure you have the following databases and exactly the same database structure as described in https://github.com/deepmind/alphafold#genetic-databases


```$DOWNLOAD_DIR/                             # Total: ~ 2.2 TB (download: 438 GB)
    bfd/                                   # ~ 1.7 TB (download: 271.6 GB)
        # 6 files.
    mgnify/                                # ~ 64 GB (download: 32.9 GB)
        mgy_clusters_2018_12.fa
    params/                                # ~ 3.5 GB (download: 3.5 GB)
        # 5 CASP14 models,
        # 5 pTM models,
        # 5 AlphaFold-Multimer models,
        # LICENSE,
        # = 16 files.
    pdb70/                                 # ~ 56 GB (download: 19.5 GB)
        # 9 files.
    pdb_mmcif/                             # ~ 206 GB (download: 46 GB)
        mmcif_files/
            # About 180,000 .cif files.
        obsolete.dat
    pdb_seqres/                            # ~ 0.2 GB (download: 0.2 GB)
        pdb_seqres.txt
    small_bfd/                             # ~ 17 GB (download: 9.6 GB)
        bfd-first_non_consensus_sequences.fasta
    uniclust30/                            # ~ 86 GB (download: 24.9 GB)
        uniclust30_2018_08/
            # 13 files.
    uniprot/                               # ~ 98.3 GB (download: 49 GB)
        uniprot.fasta
    uniref90/                              # ~ 58 GB (download: 29.7 GB)
        uniref90.fasta```

**Comment by pariskang** [comment]
Thank u for u fast reply. could u please show me the details of pdb70 database, I thought this dataset may be led to this error.
