### ISSUE TITLE
Could not find HHBlits database

### ISSUE THREAD

**Issue by karlaarz** [kalininalab/alphafold_non_docker#48]
Hi! I installed alphafold following the [non_docker option](https://github.com/kalininalab/alphafold_non_docker) using the reduced version of the databases (reduced_dbs mode), and I have this error:

```
bash run_alphafold.sh -d /home/k.ruiz/alphafold_data -o /home/k.ruiz/rnaseq/alphafold/output -f /home/k.ruiz/rnaseq/alphafold/input/MSTRG.4643.1_3_RBP3.fasta -t 2020-05-14

I0725 12:53:28.340466 140062189004608 templates.py:857] Using precomputed obsolete pdbs /home/k.ruiz/alphafold_data/pdb_mmcif/obsolete.dat.
E0725 12:53:28.343733 140062189004608 hhblits.py:82] Could not find HHBlits database /home/k.ruiz/alphafold_data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt
Traceback (most recent call last):
  File "/home/k.ruiz/alphafold-2.2.0/run_alphafold.py", line 422, in <module>
    app.run(main)
  File "/home/k.ruiz/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/k.ruiz/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/k.ruiz/alphafold-2.2.0/run_alphafold.py", line 338, in main
    monomer_data_pipeline = pipeline.DataPipeline(
  File "/home/k.ruiz/alphafold-2.2.0/alphafold/data/pipeline.py", line 138, in __init__
    self.hhblits_bfd_uniclust_runner = hhblits.HHBlits(
  File "/home/k.ruiz/alphafold-2.2.0/alphafold/data/tools/hhblits.py", line 83, in __init__
    raise ValueError(f'Could not find HHBlits database {database_path}')
ValueError: Could not find HHBlits database /home/k.ruiz/alphafold_data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt

```

However, when I try to edit the run_alphafold.py file following this [thread](https://github.com/kuixu/alphafold/issues/2#issuecomment-890273846), lines 76 and 77 look different from the ones mentioned there, as my run_alphafold.py looks like:
```
flags.DEFINE_string('uniclust30_database_path', None, 'Path to the Uniclust30 '
                    'database for use by HHblits.')
```

Is there any other solution? 

Thanks!

**Comment by Old-Shatterhand** [comment]
Hi @karlaarz 

sorry for the late response. For me, this sounds like you didn't install the datasets properly. Have you checked if there are files in `/home/k.ruiz/alphafold_data/bfd/` that have the prefix `bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt` and varying extensions?

If this does not help, you can try to reinstall the databases.

Best, Roman

**Comment by addsg** [comment]
Hi @karlaarz  
I have met the same problem as you. For me, you can add `-c reduced_dbs` in you command

**Comment by karlaarz** [comment]
Hi @addsg thanks for your comment! :)

**Comment by apal6** [comment]
Hi,

I have the same error and still not able to fix it. Would you mind helping me? 

`File "/scratch/groups/alphafold/alphafold/data/tools/hhblits.py", line 83, in __init__
    raise ValueError(f'Could not find HHBlits database {database_path}')
ValueError: Could not find HHBlits database /scratch/groups/uniref30/uniref30.fasta`

Thank you in advance.

**Comment by addsg** [comment]
hi,
if you download reduced_dbs instead of bfd database, you can try to  add -c reduced_dbs in you command. If conditions permit， I suggest you to download bfd because it will provide lots of convenient in the following steps.

**Comment by himanshue2e** [comment]
use
```YOUR_DATABASE_PATH/uniref30/UniRef30```
for uniref30 path
