### ISSUE TITLE
Minimization failed after 100 attempts.

### ISSUE THREAD

**Issue by dahaigui** [kalininalab/alphafold_non_docker#51]
The driver version is 11.7

![image](https://user-images.githubusercontent.com/47802187/192097703-4535c21a-5c21-445a-8c47-32e0af2091b9.png)

The cudatoolkit version is 11.7
![image](https://user-images.githubusercontent.com/47802187/192097745-3ac1ec8b-4ca7-4c36-a86e-5e88c63f2947.png)

I0922 20:54:25.670873 139785783146304 amber_minimize.py:407] Minimizing protein, attempt 98 of 100.
I0922 20:54:27.095493 139785783146304 amber_minimize.py:68] Restraining 5073 / 10077 particles.
I0922 20:54:27.823423 139785783146304 amber_minimize.py:417] Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)

I0922 20:54:27.830594 139785783146304 amber_minimize.py:407] Minimizing protein, attempt 99 of 100.
I0922 20:54:28.679339 139785783146304 amber_minimize.py:68] Restraining 5073 / 10077 particles.
I0922 20:54:29.414243 139785783146304 amber_minimize.py:417] Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)

I0922 20:54:29.421343 139785783146304 amber_minimize.py:407] Minimizing protein, attempt 100 of 100.
I0922 20:54:30.978424 139785783146304 amber_minimize.py:68] Restraining 5073 / 10077 particles.
I0922 20:54:31.718168 139785783146304 amber_minimize.py:417] Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)

Traceback (most recent call last):
  File "/22t/chenhx/software/alphafold-2.2.0/run_alphafold.py", line 422, in <module>
    app.run(main)
  File "/22t/chenhx/miniconda3/envs/testalphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/22t/chenhx/miniconda3/envs/testalphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/22t/chenhx/software/alphafold-2.2.0/run_alphafold.py", line 398, in main
    predict_structure(
  File "/22t/chenhx/software/alphafold-2.2.0/run_alphafold.py", line 242, in predict_structure
    relaxed_pdb_str, _, _ = amber_relaxer.process(prot=unrelaxed_protein)
  File "/22t/chenhx/software/alphafold-2.2.0/alphafold/relax/relax.py", line 61, in process
    out = amber_minimize.run_pipeline(
  File "/22t/chenhx/software/alphafold-2.2.0/alphafold/relax/amber_minimize.py", line 475, in run_pipeline
    ret = _run_one_iteration(
  File "/22t/chenhx/software/alphafold-2.2.0/alphafold/relax/amber_minimize.py", line 419, in _run_one_iteration
    raise ValueError(f"Minimization failed after {max_attempts} attempts.")
ValueError: Minimization failed after 100 attempts.

**Comment by dahaigui** [comment]
How can I address this issue?

**Comment by Old-Shatterhand** [comment]
Hi @dahaigui,

sorry for the late response. We're experiencing this issue from time to time when the input sequences are very long and AlphaFold is close to some out-of-memory issues. Can you check this out?

Anyways, have you installed AlphaFold following the description in this repo? From the trace, I can see that the program flow goes out of the conda environment.

Best, Roman

**Comment by johnsnowgo** [comment]
I met the same error with you. I solved it by set `-r false` when `bash run_alphafold.sh`. Hope it can help you.

**Comment by dahaigui** [comment]
I solved the problem, but I forgot the solution, it was roughly caused by nvrtc reporting an error, solving the dependency should be fine!
