### ISSUE TITLE
ValueError: Could not find HHsearch database

### ISSUE THREAD

**Issue by Lili-irtyd** [kalininalab/alphafold_non_docker#72]
Hi all

I meet a problem that
E0226 17:51:54.905934 139873214023488 hhsearch.py:56] Could not find HHsearch database ./alphafold_data//pdb70/pdb70
Traceback (most recent call last):
  File "/home/gpux1/alphafold/run_alphafold.py", line 432, in <module>
    app.run(main)
  File "/home/gpux1/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/gpux1/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/gpux1/alphafold/run_alphafold.py", line 337, in main
    template_searcher = hhsearch.HHSearch(
  File "/home/gpux1/alphafold/alphafold/data/tools/hhsearch.py", line 57, in __init__
    raise ValueError(f'Could not find HHsearch database {database_path}')
ValueError: Could not find HHsearch database ./alphafold_data//pdb70/pdb70

I'd like to ask if the reason for this is because my dataset is downloaded on a removable drive, while the python environment is local？

**Comment by mswiseman** [comment]
I've run into the same issue and I also have the databases on an external ssd. 

```bash
(AlphaPulldown) mswiseman@DESKTOP-E6K4A3B:/mnt/c/Users/Intel User/Desktop/alphaPulldown/main/alphafold$ python3 docker/run_docker.py --fasta_paths=cascade_dt_mlos.fasta --max_template_date=2022-05-01 --data_dir=/mnt/d/afdb/ --output_dir=/mnt/d/output/
I0310 20:48:47.222002 139999648913216 run_docker.py:116] Mounting /mnt/c/Users/Intel User/Desktop/alphaPulldown/main/alphafold -> /mnt/fasta_path_0
I0310 20:48:47.223789 139999648913216 run_docker.py:116] Mounting /mnt/d/afdb/uniref90 -> /mnt/uniref90_database_path
I0310 20:48:47.225238 139999648913216 run_docker.py:116] Mounting /mnt/d/afdb/mgnify -> /mnt/mgnify_database_path
I0310 20:48:47.226541 139999648913216 run_docker.py:116] Mounting /mnt/d/afdb -> /mnt/data_dir
I0310 20:48:47.227244 139999648913216 run_docker.py:116] Mounting /mnt/d/afdb/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0310 20:48:47.227963 139999648913216 run_docker.py:116] Mounting /mnt/d/afdb/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0310 20:48:47.228614 139999648913216 run_docker.py:116] Mounting /mnt/d/afdb/pdb70 -> /mnt/pdb70_database_path
I0310 20:48:47.229176 139999648913216 run_docker.py:116] Mounting /mnt/d/afdb/uniref30 -> /mnt/uniref30_database_path
I0310 20:48:47.230124 139999648913216 run_docker.py:116] Mounting /mnt/d/afdb/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt -> /mnt/bfd_database_path
I0310 20:48:50.188471 139999648913216 run_docker.py:258] I0311 03:48:50.186644 140645041710912 templates.py:858] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat.
I0310 20:48:50.195737 139999648913216 run_docker.py:258] E0311 03:48:50.195186 140645041710912 hhblits.py:82] Could not find HHBlits database /mnt/bfd_database_path
I0310 20:48:50.195857 139999648913216 run_docker.py:258] Traceback (most recent call last):
I0310 20:48:50.195922 139999648913216 run_docker.py:258] File "/app/alphafold/run_alphafold.py", line 570, in <module>
I0310 20:48:50.196004 139999648913216 run_docker.py:258] app.run(main)
I0310 20:48:50.196043 139999648913216 run_docker.py:258] File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 312, in run
I0310 20:48:50.196097 139999648913216 run_docker.py:258] _run_main(main, args)
I0310 20:48:50.196248 139999648913216 run_docker.py:258] File "/app/alphafold/run_alphafold.py", line 486, in main
I0310 20:48:50.196299 139999648913216 run_docker.py:258] monomer_data_pipeline = pipeline.DataPipeline(
I0310 20:48:50.196354 139999648913216 run_docker.py:258] File "/app/alphafold/alphafold/data/pipeline.py", line 138, in __init__
I0310 20:48:50.196411 139999648913216 run_docker.py:258] self.hhblits_bfd_uniref_runner = hhblits.HHBlits(
I0310 20:48:50.196465 139999648913216 run_docker.py:258] File "/app/alphafold/alphafold/data/tools/hhblits.py", line 83, in __init__
I0310 20:48:50.196544 139999648913216 run_docker.py:258] raise ValueError(f'Could not find HHBlits database {database_path}')
I0310 20:48:50.196601 139999648913216 run_docker.py:258] ValueError: Could not find HHBlits database /mnt/bfd_database_path
```

I believe I have all the databases installed correctly. 
```bash
bfd:
.  ..  ._bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt  bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt

mgnify:
.  ..  mgy_clusters_2022_05.fa

params:
.   LICENSE                                params_model_1.npz              params_model_1_ptm.npz  params_model_2_multimer_v3.npz  params_model_3.npz              params_model_3_ptm.npz  params_model_4_multimer_v3.npz  params_model_5.npz              params_model_5_ptm.npz
..  alphafold_params_2022-12-06.tar.aria2  params_model_1_multimer_v3.npz  params_model_2.npz      params_model_2_ptm.npz          params_model_3_multimer_v3.npz  params_model_4.npz      params_model_4_ptm.npz          params_model_5_multimer_v3.npz

pdb70:
.  ..  md5sum  pdb70_a3m.ffdata  pdb70_a3m.ffindex  pdb70_clu.tsv  pdb70_cs219.ffdata  pdb70_cs219.ffindex  pdb70_hhm.ffdata  pdb70_hhm.ffindex  pdb_filter.dat

pdb_mmcif:
.  ..  mmcif_files  obsolete.dat

pdb_seqres:
.  ..  pdb_seqres.txt

uniprot:
.  ..  uniprot.fasta

uniref30:
.  ..  UniRef30_2021_03.md5sums  UniRef30_2021_03_a3m.ffdata  UniRef30_2021_03_a3m.ffindex  UniRef30_2021_03_cs219.ffdata  UniRef30_2021_03_cs219.ffindex  UniRef30_2021_03_hhm.ffdata  UniRef30_2021_03_hhm.ffindex

uniref90:
.  ..  uniref90.fasta
(AlphaPulldown) mswiseman@DESKTOP-E6K4A3B:/mnt/d/afdb$ pwd
/mnt/d/afdb
```

Within bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt:
```bash
(AlphaPulldown) mswiseman@DESKTOP-E6K4A3B:/mnt/d/afdb/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt$ ls -lah
total 1.8T
drwxrwxrwx 1 mswiseman mswiseman  512 Mar  4 22:40 .
drwxrwxrwx 1 mswiseman mswiseman  512 Mar  4 17:15 ..
-rwxrwxrwx 1 mswiseman mswiseman 1.5T Mar  4 23:38 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffdata
-rwxrwxrwx 1 mswiseman mswiseman 1.7G Mar  4 23:38 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffindex
-rwxrwxrwx 1 mswiseman mswiseman  16G Mar  4 23:39 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_cs219.ffdata
-rwxrwxrwx 1 mswiseman mswiseman 1.6G Mar  4 23:39 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_cs219.ffindex
-rwxrwxrwx 1 mswiseman mswiseman 305G Mar  4 23:55 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_hhm.ffdata
-rwxrwxrwx 1 mswiseman mswiseman 124M Mar  4 23:55 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_hhm.ffindex

```

**Comment by Lili-irtyd** [comment]
Thankyou, I haven't solve it yet. If you solve it, please tell me the solution. Thanks!

**Comment by wflyerthariani** [comment]
I found out that in my case it was a permission issue. I think you can debug the problem by checking the source of the issue in the deepmind repo's [hhsearch.py](https://github.com/google-deepmind/alphafold/blob/main/alphafold/data/tools/hhsearch.py)
```
for database_path in self.databases:
      if not glob.glob(database_path + '_*'):
        logging.error('Could not find HHsearch database %s', database_path)
        raise ValueError(f'Could not find HHsearch database {database_path}')
```
Specifically I tested this `glob.glob(database_path + '_*')` to check if the script was picking up all the `/pdb70/pdb70_*` files with the wildcard search. Though I would imagine that your environment just doesn't have permission.
